### ISSUE TITLE
Göra om till en github pages?

### ISSUE THREAD

**Issue by theseal** [svenska-kafferosterier-rymdvarel-se/svenska-kafferosterier-rymdvarel-se.github.io#2]

**Comment by theseal** [comment]
Custom domain?

**Comment by simmel** [comment]
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site
https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

**Comment by simmel** [comment]
https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites

>Unless you're using a custom domain, project sites are available at http(s)://<username>.github.io/<repository> or http(s)://<organization>.github.io/<repository>.
